application:
  topic:
    from: retryapp-retrytopic
    to:
  retry-topic:
    enabled: true
  is-retry-topic-consumer: true

server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.kafka.retrytopic.consumer.EventDeserializer
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.kafka.retrytopic.producer.EventSerializer
  datasource:
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    driver-classe-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/retryapp?allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: mdymen_pass
  jpa:
    show-sql: true
  main:
    allow-circular-references: true