application:
  topic:
    from: retryapp-retrytopic
    to: retryapp-dlt
  retry-topic:
    enabled: true

server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.kafka.retrytopic.consumer.EventDeserializer
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.kafka.retrytopic.producer.EventSerializer
